package com.greate.community.entity;

/**
 * banner
 * 
 * @author ylm
 * @version 1.0.0 2023-04-21
 */
public class Banner implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2925630770168207153L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    private Integer id;

    /** url */
    private String url;

    /** img */
    private String img;

    /** title */
    private String title;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取url
     * 
     * @return url
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * 设置url
     * 
     * @param url
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * 获取img
     * 
     * @return img
     */
    public String getImg() {
        return this.img;
    }

    /**
     * 设置img
     * 
     * @param img
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * 获取title
     * 
     * @return title
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * 设置title
     * 
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}