package com.greate.community.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 * blacklist
 *
 * @author ylm
 * @version 1.0.0 2023-04-10
 */
public class BlackList {
    /** 版本号 */
    private static final long serialVersionUID = -199329564285410342L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 涉案人员 */
    private String personInvolved;

    /** 举报用户 */
    private String reportUser;

    /** 创建时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createTime;

    /** 更新时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date updateTime;

    /** 行为描述 */
    private String behaviorDescription;

    /** 涉案人员网易账户 */
    private String wyAccount;

    /** 涉案人员游戏id */
    private String accountId;

    /** id */
    private Integer id;

    /** 是否审核 */
    private Integer isAudit;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取涉案人员
     *
     * @return 涉案人员
     */
    public String getPersonInvolved() {
        return this.personInvolved;
    }

    /**
     * 设置涉案人员
     *
     * @param personInvolved
     *          涉案人员
     */
    public void setPersonInvolved(String personInvolved) {
        this.personInvolved = personInvolved;
    }

    /**
     * 获取举报用户
     *
     * @return 举报用户
     */
    public String getReportUser() {
        return this.reportUser;
    }

    /**
     * 设置举报用户
     *
     * @param reportUser
     *          举报用户
     */
    public void setReportUser(String reportUser) {
        this.reportUser = reportUser;
    }

    /**
     * 获取创建时间
     *
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取更新时间
     *
     * @return 更新时间
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置更新时间
     *
     * @param updateTime
     *          更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取行为描述
     *
     * @return 行为描述
     */
    public String getBehaviorDescription() {
        return this.behaviorDescription;
    }

    /**
     * 设置行为描述
     *
     * @param behaviorDescription
     *          行为描述
     */
    public void setBehaviorDescription(String behaviorDescription) {
        this.behaviorDescription = behaviorDescription;
    }

    /**
     * 获取涉案人员网易账户
     *
     * @return 涉案人员网易账户
     */
    public String getWyAccount() {
        return this.wyAccount;
    }

    /**
     * 设置涉案人员网易账户
     *
     * @param wyAccount
     *          涉案人员网易账户
     */
    public void setWyAccount(String wyAccount) {
        this.wyAccount = wyAccount;
    }

    /**
     * 获取涉案人员游戏id
     *
     * @return 涉案人员游戏id
     */
    public String getAccountId() {
        return this.accountId;
    }

    /**
     * 设置涉案人员游戏id
     *
     * @param accountId
     *          涉案人员游戏id
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * 获取id
     *
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取是否审核
     *
     * @return isAudit
     */
    public Integer getIsAudit() {
        return isAudit;
    }

    /**
     * 设置是否审核
     *
     * @param isAudit
     */
    public void setIsAudit(Integer isAudit) {
        this.isAudit = isAudit;
    }
    /* This code was generated by TableGo tools, mark 2 end. */
}